only_rules:
  # Spacing
  - opening_brace
  - closing_brace
  - closure_spacing
  - comma
  - colon
  # Whitespace (Xcode configuration)
  - leading_whitespace
  - let_var_whitespace
  - operator_whitespace
  - operator_usage_whitespace
  - return_arrow_whitespace

# Spacing
opening_brace:
  severity: error
closing_brace:
  severity: error
closure_spacing:
  severity: error
comma:
  severity: error
colon:
  severity: error
# Whitespace
leading_whitespace:
  severity: error
let_var_whitespace:
  severity: error
operator_whitespace:
  severity: error
operator_usage_whitespace:
  severity: error
return_arrow_whitespace:
  severity: error

# Paths to ignore
excluded:
- Pods
