name: Bug Report
description: Report a bug you encountered with the Okta OIDC SDK
labels: [ bug ]
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the bug?
      description: |
        Please be as detailed as possible. This will help us address the bug in a timely manner.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What is expected to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What is the actual behavior?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps?
      description: |
        Please provide as much detail as possible to help us reproduce your bug.
        A reproduction repo is very helpful for us as well.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information?

  - type: textarea
    id: sdkVersion
    attributes:
      label: SDK Version(s)
    validations:
      required: true

  - type: textarea
    id: buildInformation
    attributes:
      label: Build Information
      description: If this is an issue related to building, please supply Xcode version, target device type / version, and any other relevant information.
